# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0017_auto_20170216_1416'),
        ('gameapp', '0011_auto_20170216_1427'),
    ]

    operations = [
    ]
